export const cities = ["Karachi", "Lahore", "Faisalabad", "Multan", "Gujrat"];
export const Categories = ["IPhones", "Ipads", "Mackbooks", "Airpods", "Watches", "Homepods"];

export const mobileModels = [
	"iPhone 15 Pro Max",
	"iPhone 15 Pro",
	"iPhone 15 Plus",
	"iPhone 15",
	"iPhone 14 Pro Max",
	"iPhone 14 Pro",
	"iPhone 14 Plus",
	"iPhone 14",
	"iPhone 13 Pro Max",
	"iPhone 13 Pro",
	"iPhone 13 mini",
	"iPhone 13",
	"iPhone 12 Pro Max",
	"iPhone 12 Pro",
	"iPhone 12 mini",
	"iPhone 12",
	"iPhone SE ",
	"iPhone 11 Pro Max",
	"iPhone 11 Pro",
	"iPhone 11",
	"iPhone XR",
	"iPhone XS Max",
	"iPhone XS",
	"iPhone X",
	"iPhone 8 Plus",
	"iPhone 8",
	"iPhone 7 Plus",
	"iPhone 7",
	"iPhone 6S Plus",
	"iPhone 6S",
	"iPhone 6 Plus",
	"iPhone 6",
];
export const appleAirpodsModels = [
	"AirPods Gen1",
	"AirPods Gen2",
	"AirPods Gen3",
	"AirPods Pro",
	"AirPods Max",
];
export const appleMacBookModels = [
	"MacBook Pro 14-inch (M2 Pro)",
	"MacBook Pro 14-inch (M2 Max)",
	"MacBook Pro 16-inch (M2 Pro)",
	"MacBook Pro 16-inch (M2 Max)",
	"MacBook Air (M2)",
	"MacBook Pro 13-inch (M1, 2020)",
	"MacBook Air (M1, 2020)",
	"MacBook Pro 16-inch (Intel, 2019)",
	"MacBook Pro 13-inch (Intel, 2019)",
	"MacBook Air (Intel, 2018)",
	"MacBook 12-inch (Intel, 2017)",
];

export const appleWatchModels = [
	"Apple Watch Series 8 (GPS)",
	"Apple Watch Series 8 (Cellular)",
	"Apple Watch Series 8 Nike",
	"Apple Watch Series 8 (Hermes)",
	"Apple Watch SE (GPS)",
	"Apple Watch SE (Cellular)",
	"Apple Watch Series 7 (2021)",
	"Apple Watch Series 6 (2020)",
	"Apple Watch SE (2020)",
	"Apple Watch Series 5 (2019)",
	"Apple Watch Series 4 (2018)",
	"Apple Watch Series 3 (2017)",
];
export const appleHomePodModels = ["HomePod mini", "HomePod"];

export const CategoriesObj = {
	IPhones: [
		"iPhone 15 Pro Max",
		"iPhone 15 Pro",
		"iPhone 15 Plus",
		"iPhone 15",
		"iPhone 14 Pro Max",
		"iPhone 14 Pro",
		"iPhone 14 Plus",
		"iPhone 14",
		"iPhone 13 Pro Max",
		"iPhone 13 Pro",
		"iPhone 13 mini",
	],
	Ipads: ["AirPods Gen1", "AirPods Gen2", "AirPods Gen3", "AirPods Pro", "AirPods Max"],
	Airpods: ["AirPods Gen1", "AirPods Gen2", "AirPods Gen3", "AirPods Pro", "AirPods Max"],
	Mackbooks: [
		"MacBook Pro 14-inch (M2 Pro)",
		"MacBook Pro 14-inch (M2 Max)",
		"MacBook Pro 16-inch (M2 Pro)",
		"MacBook Pro 16-inch (M2 Max)",
		"MacBook Air (M2)",
		"MacBook Pro 13-inch (M1, 2020)",
	],
	Watches: [
		"Apple Watch Series 8 (GPS)",
		"Apple Watch Series 8 (Cellular)",
		"Apple Watch Series 8 Nike",
		"Apple Watch Series 8 (Hermes)",
		"Apple Watch SE (GPS)",
		"Apple Watch SE (Cellular)",
	],
	Homepods: ["HomePod mini", "HomePod"],
};

export const fullCategoriesObj = {
	IPhone: [
		"iPhone 15 Pro Max",
		"iPhone 15 Pro",
		"iPhone 15 Plus",
		"iPhone 15",
		"iPhone 14 Pro Max",
		"iPhone 14 Pro",
		"iPhone 14 Plus",
		"iPhone 14",
		"iPhone 13 Pro Max",
		"iPhone 13 Pro",
		"iPhone 13 mini",
		"iPhone 13",
		"iPhone 12 Pro Max",
		"iPhone 12 Pro",
		"iPhone 12 mini",
		"iPhone 12",
		"iPhone SE ",
		"iPhone 11 Pro Max",
		"iPhone 11 Pro",
		"iPhone 11",
		"iPhone XR",
		"iPhone XS Max",
		"iPhone XS",
		"iPhone X",
		"iPhone 8 Plus",
		"iPhone 8",
		"iPhone 7 Plus",
		"iPhone 7",
		"iPhone 6S Plus",
		"iPhone 6S",
		"iPhone 6 Plus",
		"iPhone 6",
	],
	Ipads: ["AirPods Gen1", "AirPods Gen2", "AirPods Gen3", "AirPods Pro", "AirPods Max"],
	Airpods: ["AirPods Gen1", "AirPods Gen2", "AirPods Gen3", "AirPods Pro", "AirPods Max"],
	Mackbook: [
		"MacBook Pro 14-inch (M2 Pro)",
		"MacBook Pro 14-inch (M2 Max)",
		"MacBook Pro 16-inch (M2 Pro)",
		"MacBook Pro 16-inch (M2 Max)",
		"MacBook Air (M2)",
		"MacBook Pro 13-inch (M1, 2020)",
		"MacBook Air (M1, 2020)",
		"MacBook Pro 16-inch (Intel, 2019)",
		"MacBook Pro 13-inch (Intel, 2019)",
		"MacBook Air (Intel, 2018)",
		"MacBook 12-inch (Intel, 2017)",
	],
	Watches: [
		"Apple Watch Series 8 (GPS)",
		"Apple Watch Series 8 (Cellular)",
		"Apple Watch Series 8 Nike",
		"Apple Watch Series 8 (Hermes)",
		"Apple Watch SE (GPS)",
		"Apple Watch SE (Cellular)",
		"Apple Watch Series 7 (2021)",
		"Apple Watch Series 6 (2020)",
		"Apple Watch SE (2020)",
		"Apple Watch Series 5 (2019)",
		"Apple Watch Series 4 (2018)",
		"Apple Watch Series 3 (2017)",
	],
	Homepods: ["HomePod mini", "HomePod"],
};
